default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: app_development

test:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: app_test

production:
  username: ycgwqnxrquofjj
  password: eab15d881d0a9a1de2614e074329b48012a88a567d48f238883f69fe4eb17be1
  host: ec2-18-208-55-135.compute-1.amazonaws.com
  database: ddfrv18tqt6sji
  url: postgres://ycgwqnxrquofjj:eab15d881d0a9a1de2614e074329b48012a88a567d48f238883f69fe4eb17be1@ec2-18-208-55-135.compute-1.amazonaws.com:5432/ddfrv18tqt6sji
