default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: app_development

test:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: app_test

production:
  url: postgres://gqushbvpnxkwjm:f900f0d2710e1085976b4a3584bfd08c51fd140b0a5d19a1cf114e7fd832dd38@ec2-3-219-19-205.compute-1.amazonaws.com:5432/d31mcqeg4eo5he