---
engine_version: 0.3.10
file_version: 2022-09-01 23:59:27.111161000 +03:00
resources: []
configs:
- key: header.links
  value: []
  updated_at: 2022-09-01 23:59:27.111161000 +00:00
queries:
- id: 1
  name: todo_lists
  sql_body: SELECT * FROM todo_lists
  description: todo_lists_description
  preferences:
    query_type: sql
    visualization: table
    visualization_options: {}
    variables: []
  tags: []
  updated_at: 2022-09-01 23:52:33.910571000 +00:00
dashboards:
- id: 1
  title: Todo
  description: Todo_lists
  preferences:
    layout:
    - title: todo_lists
      query_id: 1
      size: 3x2
    variables: []
    autorefresh_interval: 5000
  tags: []
  updated_at: 2022-09-01 23:52:46.442237000 +00:00
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2022-09-01 23:45:07.488725000 +00:00
